[package]
name = "minidisk-gui"
version = "0.1.0"
authors = ["SpikeHD <25207995+SpikeHD@users.noreply.github.com>"]
edition = "2021"

[dependencies]
dioxus = { version = "0.6.3", features = [] }
libatasmart-sys = "0.2.0"
libminidisk = { path = "../lib" }
sudo = "0.6.0"

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
