[application]

# App (Project) Name
name = "GlacierDiskInfo"

[bundle]
identifier = "dev.spikehd.glacierdiskinfo"
publisher = "SpikeHD"

[web.app]

# HTML title tag content
title = "GlacierDiskInfo"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
