[application]
name = "GlacierDiskInfo"

[bundle]
identifier = "dev.spikehd.glacierdiskinfo"
publisher = "SpikeHD"

[web.app]
title = "GlacierDiskInfo"

# include `assets` in web platform
[web.resource]
style = []
script = []

[web.resource.dev]
script = []
