name: Code quality and formatting

on:
  push:
    paths:
      - '.github/workflows/format.yml'
      - 'lib/**'
      - 'cli/**'
      - 'gui/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - '.github/workflows/format.yml'
      - 'lib/**'
      - 'cli/**'
      - 'gui/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Rustfmt check
        run: cargo fmt --manifest-path ./Cargo.toml --all -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      # Required for dependencies that use external libs
      - name: Install dependencies
        run: |
          sudo apt update 
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libatasmart-dev \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Clippy check
        run: cargo clippy --manifest-path ./Cargo.toml --all -- -D warnings